# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e09b0a5f1ad77268e4b8bffa145e74508995d0c9ba38326f71526e06e1c032f8044bbb7fea3d18ac70fb60d47b4c00965fc6003ba7493e3761470fd8484a72

test:
  secret_key_base: dc3b0780aac8e5b80511610efadcd163d5539d53e3572cf655b5fa19b832998c89eb5c07f0aea428d33b14ef2927e8eb1160c7cf406814044acd5f868f141283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
